name 'prometheus-stack-cookbook'
description 'Installs/Configures prometheus-stack-cookbook'
long_description 'Installs/Configures prometheus-stack-cookbook'
version '0.1.0'
chef_version '>= 13.0'
depends 'docker'